- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create incident
      servicenow.itsm.incident:
        state: new
        short_description: "A short incident description created by ansible {{ now() }}"
        description: |
          created from Ansible {{ now(fmt='%Y-%m-%d %H:%M:%S') }}
          more information
        #attachments:
        #  - path: ./create_incident.yml
        impact: low
        urgency: low
      register: incident

    - name: Show incident details
      ansible.builtin.debug:
        var: incident
        verbosity: 1

