- hosts: localhost
  gather_facts: false
  vars:
    data:
      - name: web01.example.com
        short_description: web server
        serial_number: 1234
        environment: production
      - name: web02.example.com
        short_description: web server
        serial_number: 1235
        environment: production
      - name: web03.example.com
        short_description: web server
        serial_number: 1236
        environment: test
      - name: web04.example.com
        short_description: web server
        serial_number: "{{ 99999 | random }}"
        environment: test
  tasks:
    - name: Create sample Linux servers
      servicenow.itsm.configuration_item:
        name: "{{ item.name }}"
        short_description: "{{ item.short_description }}"
        serial_number: "{{ item.serial_number }}"
        sys_class_name: cmdb_ci_server
        #assigned_to: ansible
        environment: "{{ item.environment }}"
        category: Hardware
        other:
          os: "Linux Red Hat"
          os_version: "9.4"
          fqdn: "{{ item.name }}"
          location: "Emea"
          u_business_identifier: 73
          u_business_thing: "the thing important to the business"
          virtual: "true"
      loop: "{{ data }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create a sample domain controller
      servicenow.itsm.configuration_item:
        name: "dc01.example.com"
        short_description: "example domain controller"
        sys_class_name: cmdb_ci_server
        #assigned_to: ansible
        environment: "production"
        category: Hardware
        other:
          os: "Windows"
          os_version: "2022"
          fqdn: "dc01.example.com"
          u_business_identifier: 7
          u_business_thing: "hmm"
