plugin: servicenow.itsm.now
query:
  - os: = Linux Red Hat
    operational_status: = 1
columns:
  - fqdn
  - host_name
  - ip_address
  - name
  - os
  - environment
  - location
  - used_for
  - classification
groups:
  test_rhel_servers: >-
    environment == "Test" and
    os in ("Linux Red Hat", "RHEL")

  prod_rhel_servers: >-
    environment == "Production" and
    os in ("Linux Red Hat", "RHEL")

  emea_rhel_servers: >-
    location == "Emea" and
    os in ("Linux Red Hat", "RHEL")

  custom_rhel_servers: >-
    u_business_identifier == "73" and
    os in ("Linux Red Hat", "RHEL")

  virtual_rhel_servers: >-
    virtual == "true" and
    os in ("Linux Red Hat", "RHEL")

  non_virtual_rhel_servers: >-
    virtual == "false" and
    os in ("Linux Red Hat", "RHEL")

compose:
  ansible_host: fqdn

