plugin: servicenow.itsm.now
table: cmdb_ci_linux_server
query:
  - os: = Linux Red Hat
columns:
  - fqdn
  - host_name
  - ip_address
  - name
  - os
  - environment
  # - classification
  - location
  # - u_business_identifier
  # - u_business_thing
groups:
  all_rhel_servers: os in ("Linux Red Hat", "RHEL")
  test_rhel_servers: >-
    environment == "Test" or classification == "Test" and
    os in ("Linux Red Hat", "RHEL")

  prod_rhel_servers: >-
    environment == "Production" or classification == "Production" and
    os in ("Linux Red Hat", "RHEL")

  emea_rhel_servers: >-
    location == "Emea" and
    os in ("Linux Red Hat", "RHEL")

  custom_rhel_servers: >-
    u_business_identifier == "73" and
    os in ("Linux Red Hat", "RHEL")

  virtual_rhel_servers: >-
    virtual == "true" and
    os in ("Linux Red Hat", "RHEL")

  non_virtual_rhel_servers: >-
    virtual == "false" and
    os in ("Linux Red Hat", "RHEL")
#keyed_groups:
#  - key: classification
#    separator: ""
#    prefix: "c_"
#  - key: environment
#    prefix: "environment"

compose:
  ansible_host: fqdn

