plugin: servicenow.itsm.now
enhanced: false
strict: false
query:
  - os: = Linux Red Hat
keyed_groups:
  - key: os
    prefix: 
  - key: location
    prefix:
  - key: environment
    prefix:
#compose:
#  ansible_host: fqdn
